services:
  maquina00:
    build: ./
    tty: true
    volumes:
      - /home/maquina00/bin:/bin
      - /home/maquina00/dev:/dev
      - /home/maquina00/home:/home
      - /home/maquina00/lib64:/lib64
      - /home/maquina00/opt:/opt
      - /home/maquina00/srv:/srv
      - /home/maquina00/var:/var
      - /home/maquina00/etc:/etc
      - /home/maquina00/lib:/lib
      - /home/maquina00/root:/root
      - /home/maquina00/sbin:/sbin
      - /home/maquina00/usr:/usr
    networks:
      - red00
    ports:
      - '10800:80' # HTTP
      - '14430:443' # HTTPS
      - '10210:21' # FTP
      - '19900:990' # FTPS
      - '10220:22' # SSH
      - '10070:7' # UDP
  maquina01:
    build: ./
    tty: true
    volumes:
      - /home/maquina01/bin:/bin
      - /home/maquina01/dev:/dev
      - /home/maquina01/home:/home
      - /home/maquina01/lib64:/lib64
      - /home/maquina01/opt:/opt
      - /home/maquina01/srv:/srv
      - /home/maquina01/var:/var
      - /home/maquina01/etc:/etc
      - /home/maquina01/lib:/lib
      - /home/maquina01/root:/root
      - /home/maquina01/sbin:/sbin
      - /home/maquina01/usr:/usr
    networks:
      - red00
    ports:
      - '10801:80' # HTTP
      - '14431:443' # HTTPS
      - '10211:21' # FTP
      - '19901:990' # FTPS
      - '10221:22' # SSH
      - '10071:7' # UDP
networks:
  red00: 
    driver: bridge
    external: false